### ISSUE TITLE
上传作品应添加额外信息

### ISSUE THREAD

**Issue by AdminRoc** [DawnFz/PotCopyApi#2]
- 上传作品全部需要审核   
   
   
    - 标注**原创**的作品（可填写摹本数），须一并上传（至少两项，截图需截取全屏幕）：   

        - 游戏内的个人资料界面      
        - 自己游戏内包含该摹本数的摹本数列表界面（自行涂抹隐藏其他摹本数）
        - 发布该作品的社交平台的后台界面（例如各平台的创作者中心内）
   
   
    - 标注**转载**的作品（禁止填写摹本数），须一并上传（至少两项，截图需截取全屏幕）：   
   
        - 游戏内的个人资料界面
        - 该作品的原始发布地址（例如B站视频链接）
        - 该作品的原始发布作者对于作品被分享至本站的正面同意截图   
   
   
    - 标注**二次创作**的作品（可填写摹本数），须一并上传（至少两项，截图需截取全屏幕）：   

        - 游戏内的个人资料界面
        - 该作品的原始作品地址（例如B站视频链接）
        - 该作品的原始发布作者对于作品被二次创作的正面同意截图   

（基于2022.11.17的会议讨论）

**Comment by DawnFz** [comment]
完成
