### ISSUE TITLE
添加**创作者中心**

### ISSUE THREAD

**Issue by AdminRoc** [DawnFz/PotCopyApi#3]
在管理后台中，添加**创作者中心**，即面向认证后的创作者的后台管理界面

    - 有意愿 主动支持 https://go.hut.ao/cgh 摹本数分享站的原创作者可联系站长[DawnFz](http://share.snapgenshin.com/#/about)申请**创作者中心**的账号
    
        - 基本功能设想：
            - 登录
            - 修改作者id
            - **免审核**上传与管理自己的作品，被上传作品有**独立标识**
            - 快捷处理**被举报作品**的举报条目

（基于2022.11.17的会议讨论）

**Comment by DawnFz** [comment]
完成
